### ISSUE TITLE
Travis Cron job has stopped | Reports not updated since June

### ISSUE THREAD

**Issue by OrkoHunter** [twitter/metrics#11]
Hey! I noticed that the last report was generated on [June 27](https://twitter.github.io/metrics/twitter/MONTHLY/).

Ideally, there is a cron job on Travis, which is set to run every week. The scripts then fetch the data and create these reports.

I am unsure why the Travis Cron job stopped after June 27 - https://travis-ci.com/github/twitter/metrics/builds

**Comment by willnorris** [comment]
Metrics build has now been moved to GitHub Actions, and seems to be working well, as best as I can tell.

**Comment by OrkoHunter** [comment]
Using GitHub Actions has tonnes of benefits over external CI system - just because how well it integrates.
Amazing @willnorris ! 🥳
